version: '3.7'
services:
  grafana:
    image: grafana/grafana:6.5.3
    container_name: grafana_test
    volumes:
      - "grafana-storage:/var/lib/grafana"
      - "/opt/grafana/grafana.ini:/etc/grafana/grafana.ini"
    restart: always
    expose:
      - "3000"
    networks:
      - web
    environment:
      - "GF_SERVER_DOMAIN=grafana.example.co.uk"
      - "GF_SMTP_ENABLED=true"
      - "GF_SMTP_FROM_ADDRESS=grafana@example.co.uk"
      - "GF_SMTP_HOST=smtp.local:25"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.grafana.rule=Host(`grafana.example.co.uk`)"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=le_dns"
        
networks:
  web:
    external: true

volumes:
  grafana-storage:
    external: true
          
